Recaudacion/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.views.generic import TemplateView
from applications.home.views import Error404View, Error505View
from .routers import router


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('allauth.urls')),
    
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.oficios.urls')),
    re_path('', include('applications.programacion.urls')),
    re_path('', include('applications.rec.urls')),
    re_path('', include('applications.padrones.urls')),
    re_path('', include('applications.transferidos.urls')),
    re_path('', include('applications.promocion.urls')),
    re_path('', include('applications.direccion.urls')),
    re_path('', include('applications.juridico.urls')),
    re_path('', include('applications.quinielas.urls')),
    re_path('', include('applications.saladejuntas.urls')),
    re_path('', include('applications.tramites.urls')),
    re_path('', include('applications.verificacion_vehicular.urls')),
    
    path('api/', include(router.urls)),
    path('modelos/', TemplateView.as_view(template_name='programacion/modelos.html')),
    re_path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = Error404View.as_view()
handler500 = Error505View.as_error_view()

applications/juridico/urls.py
from django.urls import path

from . import views

app_name = "juridico_app"

urlpatterns = [
    path('juridico/', views.Demanda_View.as_view(), name='juridico'),
    #     path('creacion/', views.panelJuridico.as_view(), name='panel-juridico'),
    path('alta-demanda/', views.Alta_Demanda.as_view(), name='alta-demanda'),
    path('edita-demanda/<int:pk>/', views.Edita_Demanda.as_view(), name='edita-demanda'),
    # path('alta-demanda/#profile1', views.Alta_Demanda.as_view(), name='alta-demanda'),
    # path('alta-detalle/', views.Alta_Detalle.as_view(), name='alta-detalle'),
    path('demanda/<int:id>/', views.Detalle_Demanda.as_view(),
         name='detalle-demanda'),
    path('ver-demanda/<int:pk>/',
         views.Ver_Detalle_Demanda.as_view(), name='ver-demanda'),
    path('plantilla/<str:id_juicio>/<str:id_subtipo>/<str:fecha_notificacion>/<str:fecha_aviso>/',
         views.PlantillaView.as_view(), name='plantilla'),
    path('plantilla/<str:id_juicio>/<str:id_subtipo>/<str:fecha_notificacion>/',
         views.PlantillaView.as_view(), name='plantilla'),
    path('home_Juridico/', views.InicioEjecucionView.as_view(), name='home_Juridico'),

    # Administart Demanda
    path(
        'admin-demanda/<int:pk>/',
        views.Admin_Demanda.as_view(),
        name='admin-demanda'
    ),
    path(
        'alta-proceso/<int:formulario_id>/<int:demanda>/<int:padre>/<int:rubro>',
        views.Alta_Formulario.as_view(),
        name='alta-proceso'
    ),
    path(
        'subir-archivos-juridico/<int:pk>/',
        views.Subir_Archivos.as_view(),
        name='subir-archivos-juridico'
    ),
    path(
        'get-files-juridico/<int:pk>/',
        views.Get_Files.as_view(),
        name='get-files-juridico'
    ),
    path(
        'eliminar-archivo-juridico/<int:pk>/',
        views.Eliminar_Archivo.as_view(),
        name='eliminar-archivo-juridico'
    ),
    path(
    'ver-detalle-proceso/<int:proceso>/<int:formulario>/',
    views.Ver_Detalle_Proceso.as_view(),
    name='ver-detalle-proceso'
    ),
    path(
    'actualiza-detalle-proceso/<int:proceso>/<int:formulario>/',
    views.Actualiza_Detalle_Proceso.as_view(),
    name='actualiza-detalle-proceso'
    ),
    path(
    'elimina-demanda/<int:pk>/',
    views.Elimina_Demanda.as_view(),
    name='elimina-demanda'
    ),
    path(
    'computo-proceso/<str:proceso>/<str:notificacion>/',
    views.Computo_Proceso.as_view(),
    name='computo-proceso'
    ),
    path(
    'elimina-proceso/',
    views.Elimina_Proceso,
    name='elimina-proceso'
    ),
    path(
    'expediente-modal/',
    views.Expediente.as_view(),
    name='expediente-modal'
    ),
    path('demanda/json/', views.demanda_json, name='demanda_json'),
    path('demanda-page/', views.demanda_page, name='demanda_page'),

    #"""RESOLUTOR"""
        #"""CAPTURA"""
    path('juridico/resolutor/solicitante', views.Solicitantes.as_view(), name='alta_solicitante'),
    path('juridico/resolutor/solicitante/<int:pk>/', views.SolicitanteActualiza.as_view(), name='actualiza_solicitante'),
    path('juridico/resolutor/alta', views.Resolutores.as_view(), name='alta_resolutor'),
    path('juridico/resolutor/actualiza/<int:pk>/', views.ResolutorActualiza.as_view(), name='actualiza_resolutor'),
    path('juridico/getSolicitante/<str:kword>/', views.resolutor_solicitante.as_view(), name='getSolicitante'),
    path('juridico/getSolicitanteId/<int:kword>/', views.resolutor_solicitanteId.as_view(), name='getSolicitanteId'),
    path('juridico/solicitanteActivo/', views.BuscarSolicitante, name='solicitanteActivo'),
        #"""PANEL"""
    path('juridico/resolutor', views.PanelResolutorView.as_view(), name='panel-resolutor'),
    path('asignar-abogados/', views.AsignarAbogados, name='asignar-abogados'),
    path('buscar-abogados-asignados/', views.BuscarAbogadosAsignados, name='buscar-abogados-asignados'),   
        #"""DETALLE"""
    path('juridico/resolutor/detalle/<int:pk>/', views.Ver_detalle_resolutor.as_view(), name='resolutor-detalle'),
    path('juridico/resolutor/detalle/elimina/<int:pk>/', views.Elimina_detalle.as_view(), name='detalle-eliminar'),
    path('juridico/resolutor/detalle/agregar/', views.AgregarDetalle, name='detalle-agregar'),
    path('juridico/resolutor/detalle/agregar/archivo/<int:pk>/<int:fk>/', views.Resolutor_AltaArchivo.as_view(), name='resolutorArchivo-alta'),
    path('juridico/resolutor/detalle/agregar/archivo/ejecucion/<int:pk>/<int:fk>/', views.Resolutor_AltaArchivo.as_view(), name='resolutorArchivo-alta'),
    path('juridico/resolutor/detalle/requisito/abogado/<int:pk>/', views.Resolutor_detalleList.as_view(), name='resolutorDetalle'),
    path('juridico/resolutor/detalle/requisito/ejecutor/<int:pk>/', views.Resolutor_ejecucion.as_view(), name='resolutorEjecucion'),
    path('juridico/resolutor/lectura/<int:pk>/', views.Resolutor_lectura.as_view(), name='resolutorLectura'),
        #"""REQUISITOS"""
    path('juridico/resolutor/revision/<int:pk>/', views.Resolutor_Revision.as_view(), name='resolutorRevision'),
    path('juridico/resolutor/aceptar/<int:pk>/', views.Resolutor_Aceptar, name='resolutorAceptar'),
    path('juridico/resolutor/rechazar/<int:pk>/', views.Resolutor_Rechazar, name='resolutorRechazar'),
    path('juridico/resolutor/requisito/alta/<int:pk>/', views.Resolutor_AltaRequisito.as_view(), name='resolutorRequisito-alta'),
    path('juridico/resolutor/requisito/actualiza/<int:pk>/', views.Resolutor_ActualizaRequisito.as_view(), name='resolutorRequisito-actualiza'),
    path('juridico/resolutor/requisito/elimina/<int:pk>/', views.Resolutor_EliminaRequisito, name='resolutorRequisito-elimina'),
        #"""REPORTERIA Y FIRMA"""
    path('generate/refrendo/<int:pk>/', views.generatePdfRefrendo, name='resolutorRefrendo'),
    path('generate/tenencia/<int:pk>/', views.generatePdfTenencia, name='resolutorTenencia'),
    path('generate/refrendo/tenencia/<int:pk>/', views.generatePdfRefrendoTenencia, name='resolutorgeneratePdfRefrendoTenencia'),
    path('juridico/resolutor/firma/<int:pk>/', views.Resolutor_Firma, name='resolutorFirma'),
    path('juridico/resolutor/reportes/<int:pk>/', views.Resolutor_AltaReporte.as_view(), name='cargaReportes'),
    path('juridico/resolutor/concluir/manual/<int:pk>/', views.ConcluirManual, name='concluirManual'),








    
]

applications/juridico/forms.py
from django import forms
from django.db.models import Q
from applications.home.models import Municipio
import datetime

from applications.juridico.models import Catalogo, Demanda, Rubros, Solicitante, Resolutor, Resolutor_detalle, Requisitos
from applications.users.models import User

class Form_Demanda(forms.ModelForm):
    juicio = forms.ModelChoiceField(
        queryset = Catalogo.objects.filter(Q(agrupador= 'SELECT_JUICIO') ),
        label='Juicio',
        initial=0,
        required=True,
        widget=forms.Select(
            attrs={
                'class': 'selectize-select sin-borde',
                'placeholder' : 'Tipo juicio',
                'onChange': 'tipojuicio(this)',                
            }
        )
    )
    carpeta = forms.CharField(
        max_length=100,
        label = 'Carpeta',
        required = False,
        widget = forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    subtipo = forms.ModelChoiceField(
        queryset=Catalogo.objects.filter(Q(agrupador='SELECT_SUBTIPO')),
        label='Subtipo',
        initial=0,
        required=True,
        widget=forms.Select(
            attrs={
                'class': 'form-control selectize-select',
                'placeholder' : 'Subtipo juicio',
                'onChange': 'tipo_computo(this)',
            }
        )
    )
    expediente = forms.CharField(
        max_length=100,
        label = 'Expediente',
        required = True,
        widget = forms.TextInput(
            attrs={
                'class': 'form-control input-rec float-label',
                'placeholder' : ' ',

            }
        )
    )
    tribunal = forms.ModelChoiceField(
        queryset= Catalogo.objects.filter(Q(agrupador = 'SELECT_TRIBUNAL')),
        label='Tribunal',
        initial=0,
        required=True,
        widget=forms.Select(
            attrs={
                'class': 'form-control selectize-select',
                'placeholder' : 'Tribunal',
            }
        )
    )
    fecha_aviso = forms.DateField(
        label='Fecha aviso',
        required=False,
        widget=forms.DateInput(
            attrs={
                'class': 'form-control input-rec date-picker-default',
                'placeholder' : ' ',
                'readonly': 'readonly',
                'data-date-format': 'dd/mm/yyyy'
            }
        )
    )
    fecha_notificacion = forms.DateField(
        label='Fecha notificacion',
        required=True,
        widget=forms.DateInput(
            attrs={
                'class': 'form-control input-rec date-picker-default',
                'placeholder' : ' ',
                'readonly': 'readonly',
                'data-date-format': 'dd/mm/yyyy'
            }
        )
    )
    fecha_fatal = forms.DateField(
        label='Fecha fatal',
        required=True,
        widget=forms.DateInput(
            attrs={
                'class': 'form-control input-rec date-picker-default',
                'placeholder' : ' ',
                'readonly': 'readonly',
                'data-date-format': 'dd/mm/yyyy'
            }
        )
    )
    fecha_interno = forms.DateField(
        label='Fecha interno',
        required=True,
        widget=forms.DateInput(
            attrs={
                'class': 'form-control input-rec date-picker-default',
                'placeholder' : ' ',
                'readonly': 'readonly',
                'data-date-format': 'dd/mm/yyyy'
            }
        )
    )
    dictaminador = forms.ModelChoiceField(
        queryset= User.objects.filter(areas_id = 4, groups__name__contains='Dictaminador'),    
        label='Abogado',
        initial=0,
        required=True,
        widget=forms.Select(
            attrs={
                'class': 'form-control selectize-select',
                'placeholder' : 'Abogado dictaminador',
            }
        )
    )
    estado_procesal = forms.ModelChoiceField(
        queryset= Catalogo.objects.filter(agrupador = 'ESTADO_PROCESAL', sort = 1),
        label='Estado',
        initial=0,
        widget=forms.Select(
            attrs={
                'class': 'selectize-select sin-borde'
            }
        )
    )
    autoridad = forms.ModelChoiceField(
        queryset= Catalogo.objects.filter(Q(agrupador='SELECT_AUTORIDAD')),
        label='Autoridad',
        initial=0,
        required=False,
        widget=forms.Select(
            attrs={
                'class': 'form-control selectize-select',
                'placeholder' : 'Autoridad',
            }
        )
    )
    resolucion_impg = forms.CharField(
        max_length=100,
        label = 'Resolucion impugnada',
        required = False,
        widget = forms.TextInput(
            attrs={
                'class': 'form-control input-rec float-label',
                'placeholder' : ' ',
            }
        )
    )
    cuantia = forms.DecimalField(
        max_digits=12,
        decimal_places=2,
        label = 'Cuantia',
        required = False,
        widget = forms.TextInput(
            attrs={
                'class': 'form-control input-rec float-label',
                'onChange': 'validaCampo(this)',
                'placeholder' : ' ',
            }
        )
    )
    materia = forms.ModelChoiceField(
        queryset= Catalogo.objects.filter(Q(agrupador='SELECT_MATERIA')),
        label='Materia',
        initial=0,
        required=False,
        widget=forms.Select(
            attrs={
                'class': 'form-control selectize-select',
                'placeholder' : 'Materia',
            }
        )
    )
    contribuyente = forms.CharField(
        max_length=100,
        label = 'Contribuyente',
        required = False,
        widget = forms.TextInput(
            attrs={
                'class': 'form-control input-rec float-label',
                'placeholder' : ' ',
            }
        )
    )
    rfc  = forms.CharField(        
        label = 'RFC',
        required = True,
        widget = forms.TextInput(
            attrs={
                'class': 'form-control input-rec float-label',
                'placeholder' : ' ',
                'style': "text-transform:uppercase",
            }
        )
    )
    abogado_prom = forms.ModelChoiceField(
        queryset= Catalogo.objects.filter(Q(agrupador='SELECT_PROMOVENTE')),
        label='Abogado_Prom',
        initial=0,
        required=False,
        widget=forms.Select(
            attrs={
                'class': 'form-control selectize-select',
                'placeholder' : 'Abogado promovente',
            }
        )
    )
    fecha_resolucion = forms.DateField(
        label='fecha_resolucion',
        required=False,
        widget=forms.DateInput(
            attrs={
                'class': 'form-control date-picker-default input-rec float-label',
                'placeholder' : ' ',
                'readonly': 'readonly',
                'data-date-format': 'dd/mm/yyyy'
            }
        )
    )
    resolucion_rec  = forms.CharField(
        max_length=100,
        required=False,
        label = 'Resolucion recurrida',
        widget = forms.TextInput(
            attrs={
                'class': 'form-control input-rec float-label',
                'placeholder' : ' ',
            }
        )
    )
    autoridad_rec = forms.ModelChoiceField(
        queryset= Catalogo.objects.filter(Q(agrupador='SELECT_AUTORIDAD')),
        label='Autoridad_Rec',
        initial=0,
        required=False,
        widget=forms.Select(
            attrs={
                'class': 'form-control selectize-select',
                'placeholder' : 'Autoridad recurrida',
            }
        )
    )

    class Meta: 
        model = Demanda
        fields = ['juicio','carpeta','subtipo','expediente','tribunal','fecha_aviso','fecha_notificacion','fecha_fatal','fecha_interno',
                    'dictaminador', 'estado_procesal', 'autoridad', 'resolucion_impg','cuantia','materia', 'contribuyente','rfc', 'abogado_prom',
                    'fecha_resolucion','resolucion_rec', 'autoridad_rec']

"""" FORMULARIO EDITA DEMANDA """
class Form_Edita_Demanda(forms.ModelForm):
    #SE AGREGAN NUEVO FORMATO #
    juicio = forms.ModelChoiceField(
        queryset = Catalogo.objects.filter(Q(agrupador= 'SELECT_JUICIO') ),
        label='Juicio',
        initial=0,
        widget=forms.Select(
            attrs={
                'class': 'selectize-select sin-borde',
                'placeholder' : ' ',
                'onChange': 'tipojuicio(this)',
            }
        )
    )
    # carpeta = forms.CharField(
    #     max_length=100,
    #     label = 'Carpeta',
    #     required = False,
    #     widget = forms.TextInput(
    #         attrs={
    #             'class': 'form-control'
    #         }
    #     )
    # )
    subtipo = forms.ModelChoiceField(
        queryset=Catalogo.objects.filter(Q(agrupador='SELECT_SUBTIPO')),
        label='Subtipo',
        initial=0,
        widget=forms.Select(
            attrs={
                'class': 'form-control selectize-select'
                ,'onChange': 'tipo_computo(this)'
            }
        )
    )
    expediente = forms.CharField(
        max_length=100,
        label = 'Expediente',
        required = True,
        widget = forms.TextInput(
            attrs={
                'class': 'form-control input-rec float-label',
                'placeholder' : ' ',
            }
        )
    )
    tribunal = forms.ModelChoiceField(
        queryset= Catalogo.objects.filter(Q(agrupador = 'SELECT_TRIBUNAL')),
        label='Tribunal',
        required=False,
        initial=0,
        widget=forms.Select(
            attrs={
                'class': 'form-control selectize-select',
                'placeholder' : 'Tribunal',
            }
        )
    )
    fecha_aviso = forms.DateField(
        label='Fecha aviso',
        required=False,

templates/juridico/consultar/detalle_demanda.html
{% extends 'base_new.html' %}
{% load static %}
{% load tags %}
{% load permissions %}
{% load humanize %}
{% load l10n %}

{% block title %} Datos Juicio {% endblock title %}

{% block head %}
{% endblock head %}

{% block content %}
<div class="row">
    {% has_perms request.user 'change_visita' as change_visita %}
    {% has_perms request.user 'delete_visita' as delete_visita %}

    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                {% for campo in forms %}
                {% ifchanged campo.detalle %}
                <button type="button"
                    onclick="View_Modal('{% url 'juridico_app:alta-proceso' campo.detalle.id demanda 0 0%}')"
                    class="btn btn-primary rounded-pill" target="_blank">
                    <i class="fa fa-plus"></i> {{campo.detalle|lower}}
                </button>
                {% endifchanged %}
                {% endfor %}                
                {% for demanda in detalleDemanda %}
                {% if demanda.fecha_contestacion is None or demanda.oficio is None %}
                <button type="button"
                    onclick="View_Modal('{% url 'juridico_app:alta-proceso' 1 demanda.id 0 0%}')"
                    class="btn btn-primary rounded-pill" target="_blank">
                    <i class="fa fa-plus"></i> Contestacion
                </button>
                {% else %}
                <button type="button"
                    onclick="View_Modal('{% url 'juridico_app:alta-proceso' 129 demanda.id 0 0%}')"
                    class="btn btn-primary rounded-pill" target="_blank">
                    <i class="fa fa-plus"></i> Proceso
                </button>
                {% comment %} <select class=""
                    name="combo_Proceso"
                    id="combo_Procesos"
                    onchange="myFunction(this)">
                    <option value="Seleccionar">Seleccionar</option>
                    {% for combo in opcion %}
                        <option value="{{ combo.id }}">{{ combo.auxiliar }}</option>
                    {% endfor %}
                </select> {% endcomment %}
                {% endif %}
                {% endfor %}
                <a href="{% url 'juridico_app:juridico' %}" 
                    class="btn btn-primary  rounded-pill">
                    <i class="fa fa-reply"></i> Volver
                </a>
            </div>
            <h4 class="page-title">Datos de Juicio</h4>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 mb-30">
        <div class="card p-3">
            {% for elemento in detalleDemanda %}
            <div class="row mb-3">
                <div class="col">
                    <label><strong>No. Carpeta:</strong></label>
                    <label>{{ elemento.carpeta }}</label>
                </div>
                <div class="col">
                    <label><strong>No. Expediente:</strong></label>
                    <label>{{ elemento.expediente }}</label>
                </div>
            </div>
            <div class="row mb-3">          
                <div class="col">
                    <label><strong>Juicio:</strong></label>
                    <label>{{ elemento.juicio }}</label>
                </div>
                <div class="col">
                    <label><strong>Subtipo:</strong></label>
                    <label>{{ elemento.subtipo }}</label>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <label><strong>Tribunal:</strong></label>
                    <label>{{ elemento.tribunal }}</label>
                </div>
                <div class="col">
                    <label><strong>Estado Procesal:</strong></label>
                    <label>{{ elemento.estado_procesal }}</label>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <label><strong>Abogado Dicatminador:</strong></label>
                    <label>{{ elemento.dictaminador }}</label>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 mb-30">
        <div class="card p-3">
            <h4>Crea Procesos</h4>  
            <select class="form-control"
                name="select_proceso"
                id="idProceso"
                onchange="myFunction(this)">
                <option value="Seleccionar">Seleccionar</option>                                
                {% for combo in opcion %}
                    <option value="{{ combo.formulario }}">{{ combo.nombre }}</option>                    
                {% endfor %}
            </select>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-12 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body">
                <div class="table-responsive mt-15">
                    <table id="datatable1" class="table table-sm table-striped table-bordered p-0">
                        <thead>
                            <tr class="text-dark">
                                <th>Estado</th>
                                <th>Comentarios</th>
                                <th>Fecha</th>
                                <th>Archivo</th>
                                </tr>
                            </tr>
                        </thead>
                        <tbody>
                            {% for proceso in procesal %}
                            <tr>
                              <td>{{ proceso.procesal.nombre }}</td>
                              <td>
                                {% if proceso.comentario != None %} 
                                {{ proceso.comentario }} {% endif %}
                              </td>
                              <td>{{ proceso.updated_at|date:'d/m/Y' }}</td>
                              <td><a href=""
                                title="Proceso" tabindex="0" data-plugin="tippy" data-tippy-placement="top"
                                class="btn btn-info btn-xs" target="_self">
                                <i class="fas fa-file"></i></a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- Modal Payments -->
<div class="modal fade" id="mdView" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
</div>
{% endblock content %}

{% block extrajs %}
<script src="{% static 'assets/libs/flatpickr/flatpickr.min.js' %}"></script>
<script src="{% static 'assets/libs/spectrum-colorpicker2/spectrum.min.js' %}"></script>
<script src="{% static 'assets/libs/clockpicker/bootstrap-clockpicker.min.js' %}"></script>
<script src="{% static 'assets/libs/bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>

<script src="{% static 'assets/libs/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'assets/libs/datatables.net-bs5/js/dataTables.bootstrap5.min.js' %}"></script>
<script src="{% static 'assets/libs/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'assets/libs/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js' %}"></script>
<script src="{% static 'assets/libs/sweetalert2/sweetalert2.all.min.js' %}"></script>
<script src="{% static 'assets/libs/toastr/nuget/content/scripts/toastr.min.js' %}"></script>

<!-- Init js-->
<script src="{% static 'assets/js/pages/form-pickers.init.js' %}"></script>

<script>
    $(document).ready(function () {

        {% if messages %}
            {% for message in messages %}

                //Swal.fire({
                //    position: "top-center",
                //    icon: "success",
                //    title: '{{ message|safe }}!',
                //    showConfirmButton: !1,
                //});

                toastr.success('{{ message|safe }}', 'Éxito', {positionClass: "toast-bottom-right"})
               
            {% endfor %}
        {% endif %}
                    
        $('.alert-success').fadeOut(6000);
              
    });
        
    function Agregar_Visita(myURL) {
        $('#mdView').load(myURL, function () {

            $('.date-picker-default').datepicker({ 
                format: 'dd/mm/yyyy' 
            });
            $('.date-picker-default').css("background-color", "#f6f7f8");

            $(this).modal('show');

        });
    }

    function Editar_Visita(myURL) {
        $('#mdView').load(myURL, function () {

            $('.date-picker-default').datepicker({
                format: 'dd/mm/yyyy'
            });
            $('.date-picker-default').css("background-color", "#f6f7f8");

            $(this).modal('show');
        });
    }

    function Eliminar_Visita(myURL, myID){
        Swal.fire({
            title: 'Seguro que desea eliminar?',
            text: "este contribuyente!",
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Aceptar",
            cancelButtonText: 'Cancelar',
        }).then(function (e) {
            if (e.value) {
                $.ajax({
                    data: {
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                    },
                    url: myURL,
                    type: "POST",
                    success: function (response) {
                        console.log(response);
                        location.reload();  
                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            }
        });

    }
    
    function Ver(a){
        console.log(a);
    }
    
    function View_Modal(myURL) {
        $('#mdView').load(myURL, function () {

            $(this).modal('show');
        });
    }

    function myFunction(a) {
        View_Modal('/alta-proceso/'+a.value+'/'+{{demanda}}+'/'+0+'/'+0)
    }
    
</script>
{% endblock extrajs %}