Recaudacion/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.views.generic import TemplateView
from applications.home.views import Error404View, Error505View
from .routers import router


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('allauth.urls')),
    
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.oficios.urls')),
    re_path('', include('applications.programacion.urls')),
    re_path('', include('applications.rec.urls')),
    re_path('', include('applications.padrones.urls')),
    re_path('', include('applications.transferidos.urls')),
    re_path('', include('applications.promocion.urls')),
    re_path('', include('applications.direccion.urls')),
    re_path('', include('applications.juridico.urls')),
    re_path('', include('applications.quinielas.urls')),
    re_path('', include('applications.saladejuntas.urls')),
    re_path('', include('applications.tramites.urls')),
    re_path('', include('applications.verificacion_vehicular.urls')),
    
    path('api/', include(router.urls)),
    path('modelos/', TemplateView.as_view(template_name='programacion/modelos.html')),
    re_path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = Error404View.as_view()
handler500 = Error505View.as_error_view()

applications/programacion/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from . import functions

app_name = "programacion_app"

urlpatterns = [
    path('lista-programacion/', views.Lista_Programacion.as_view(), name='lista-programacion'),
    path('seguimiento-vigilancia/', views.Seguimiento_Vigilancia.as_view(), name='seguimiento-vigilancia'),
    path('lista-concluidos/', views.Lista_Concluidos.as_view(), name='lista-concluidos'),
    path('transferencias/', views.Lista_Transferencias.as_view(), name='transferencias'),
    path('admin-programacion/<id>/', views.Admin_Programacion.as_view(), name='admin-programacion'),
    path('ultimos-movimientos/', views.Ultimos_Movimientos.as_view(), name='ultimos-movimientos/'),
    
    path('ver-programacion/<int:pk>/', views.Ver_Programacion.as_view(), name='ver-programacion'),
    path('ver-archivos/<int:pk>/', views.Ver_Archivos.as_view(), name='ver-archivos'),
    path('ver-pagos/<int:pk>/', views.Ver_Pagos.as_view(), name='ver-pagos'),
    
    path('ver-reporte/<int:pk>/', views.Ver_Reporte.as_view(), name='ver-reporte'),
    path('ver-reporte-2/<int:pk>/', views.Ver_Reporte_2.as_view(), name='ver-reporte-2'),
    path('ver-todo/<int:pk>/', views.Ver_Todo.as_view(), name='ver-todo'),
    
    path('alta-programacion/', views.Alta_Programacion.as_view(), name='alta-programacion'),
    
    path('alta-detalle/<int:pk>/', views.Alta_Detalle.as_view(), name='alta-detalle'),
    path('alta-cierre/<int:pk>/', views.Alta_Cierre.as_view(), name='alta-cierre'),
    path('alta-solicitud/<int:pk>/', views.Alta_Solicitud.as_view(), name='alta-solicitud'),
    path('cierre-apoyo/<int:pk>/', views.Cierre_Apoyo.as_view(), name='cierre-apoyo'),
    path('estatus-cierre/<int:pk>/', views.EstatusCierreView.as_view(), name='estatus-cierre'),
    
    path('alta-archivos/<int:pk>/', views.Alta_Archivos.as_view(), name='alta-archivos'),
    path('alta-archivos-ejecucion/<int:pk>/', views.Alta_Archivos2.as_view(), name='alta-archivos-ejecucion'),
    path('alta-archivos-solicitud/<int:pk>/', views.Alta_Archivos_Solicitud.as_view(), name='alta-archivos-solicitud'),

    path('alta-pagos/<int:pk>/', views.Alta_Pagos.as_view(), name='alta-pagos'),

    path('editar-pago/<int:pk>/', views.Editar_Pago.as_view(), name='editar-pago'),
    path('editar-detalle/<int:pk>/', views.Editar_Detalle.as_view(), name='editar-detalle'),
    path('editar-archivo/<int:pk>/', views.Editar_Archivo.as_view(), name='editar-archivo'),
    path('editar-archivo-solicitud/<int:pk>/', views.Editar_Archivo_Solicitud.as_view(), name='editar-archivo-solicitud'),

    path('autorizacion/', views.Lista_Autorizacion.as_view(), name='autorizacion'),
    path('alta-contribuyente/', views.Alta_Contribuyente.as_view(), name='alta-contribuyente'),
    path('elegir/<int:pk>/', views.Elegir_Contribuyente.as_view(), name='elegir'),
    path('impuestos/<int:pk>/', views.ImpuestosView.as_view(), name='impuestos'),

    path('terminar/<int:pk>/', views.Terminar_Contribuyente.as_view(), name='terminar'),
    path('editar-contribuyente/<int:pk>/', views.Editar_Contribuyente.as_view(), name='editar-contribuyente'),
    path('get-contribuyente/<rfc>/', views.Get_Contribuyente.as_view(), name='get-contribuyente'),
    path('ver-autorizacion/<int:pk>/', views.Ver_Autorizacion.as_view(), name='ver-autorizacion'),
    path('asignar/', views.Asignar.as_view(), name='asignar'),
    path('reasignar/', views.Reasignar.as_view(), name='reasignar'),
    
    path('eliminar-archivo/<int:pk>/', views.Eliminar_Archivo.as_view(), name='eliminar-archivo'),
    path('eliminar-detalle/<int:pk>/', views.Eliminar_Detalle.as_view(), name='eliminar-detalle'),
    path('eliminar-pago/<int:pk>/', views.Eliminar_Pagos.as_view(), name='eliminar-pago'),
    
    path('cerrar-rfc/<int:pk>/', views.CerrarRFCView.as_view(), name='cerrar-rfc'),

    path('validar-dato/<str:rfc>/<int:opcion>/', views.Validar_Contribuyente.as_view(), name='validar-dato'),
    path('admin-impuestos/<str:rfc>/<str:impuesto>/', views.Admin_Impuestos.as_view(), name='admin-impuestos'),

    path(
        'subir-archivos-programacion/<int:pk>/', 
        views.Subir_Archivos_Programacion.as_view(), 
        name='subir-archivos-programacion'
    ),
    path(
        'get-files-programacion/<int:pk>/',
        views.Get_Files_Programacion.as_view(),
        name='get-files-programacion'
    ),
    path(
        'eliminar-archivo-programacion/<int:pk>/',
        views.Eliminar_Archivo_Programacion.as_view(),
        name='eliminar-archivo-programacion'
    ),
    path(
        'guardar-archivos-programacion/', 
        views.Guardar_Archivos_Programacion.as_view(), 
        name='guardar-archivos-programacion'
    ),

    path(
        'subir-archivos-vigilancia/<int:pk>/', 
        views.Subir_Archivos_Vigilancia.as_view(), 
        name='subir-archivos-vigilancia'
    ),
    path(
        'get-files-vigilancia/<int:pk>/',
        views.Get_Files_Vigilancia.as_view(),
        name='get-files-vigilancia'
    ),
    path(
        'eliminar-archivo-vigilancia/<int:pk>/',
        views.Eliminar_Archivo_Vigilancia.as_view(),
        name='eliminar-archivo-vigilancia'
    ),
    path(
        'guardar-archivos-vigilancia/', 
        views.Guardar_Archivos_Vigilancia.as_view(), 
        name='guardar-archivos-vigilancia'
    ),
    path(
        'exportar-plan-pagos/', 
        views.ExportarPlanPagos,
        name='exportar-plan-pagos'
    ),
    path(
        'exportar-seguimiento/', 
        views.ExportarSeguimiento,
        name='exportar-seguimiento'
    ),
    path(
        'excel-ultimos-movimientos/', 
        functions.ultimos_movimientos,
        name='excel-ultimos-movimientos'
    ),
    path('contribuyemte/agregar/', views.Agregar_Contribuyente.as_view(), name='add-contribuyente'),    
]

applications/rec/models.py
import os
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings

from applications.programacion.models import Programa
from applications.users.models import User
from .managers import ContactoManager, RECManager
from .coordinates import get_exif_location, get_exif_data
from .signals import optimize_image
from model_utils.models import TimeStampedModel


class Fiscalizados(TimeStampedModel):
    rfc = models.CharField('RFC', max_length=20, unique=True)
    fecha_alta = models.DateField('Fecha', blank=True)
    is_active = models.BooleanField('Estatus', default=True)
    usuario = models.CharField('Usuario', max_length=100, blank=True)

    class Meta:
        verbose_name = 'RFC No Fiscalizados'
        verbose_name_plural = 'Fiscalizados'
        ordering = ['rfc']

    def __str__(self):
        return self.rfc
        
        

class REC(models.Model):
    """ Model REC """

    rfc = models.CharField('RFC', max_length=20, unique=True)
    correo = models.EmailField('Correo', max_length=100, blank=True, null=True)
    telefono = models.CharField('Telefono', max_length=20, blank=True, null=True)
    nombre = models.CharField('Nombre', max_length=254, blank=True, null=True)
    direccion = models.CharField('Direccion', max_length=254, blank=True, null=True)
    fecha_alta = models.DateField('Fecha Alta', blank=True, null=True)

    objects = RECManager()

    class Meta:
        verbose_name = 'REC'
        verbose_name_plural = 'REC'
        ordering = ['rfc']
        
    def __str__(self):
        return str(self.rfc)


class REC_Notificados(TimeStampedModel):
    """ Model REC """

    rfc = models.CharField('RFC', max_length=20, unique=True)
    nombre = models.CharField('Nombre', max_length=254, blank=True, null=True)
    direccion = models.CharField('Direccion', max_length=254, blank=True, null=True)

    class Meta:
        verbose_name = 'REC Notificados'
        verbose_name_plural = 'REC Notificados'
        ordering = ['rfc']
        
    def __str__(self):
        return self.rfc
        
        
class Busquedas(models.Model):
    busqueda = models.CharField('Busqueda', max_length=200, blank=True)
    usuario = models.CharField(
        'Usuario',  max_length=100, blank=True)
    fecha = models.DateField('Fecha', blank=True)
    is_success = models.BooleanField('Exito', blank=True, default=False)

    class Meta:
        verbose_name = 'Busquedas'
        verbose_name_plural = 'Busquedas'
        ordering = ['busqueda']

    def __str__(self):
        return self.busqueda
        
        
        
class Registro_Civil(models.Model):
    busqueda = models.CharField('Busqueda', max_length=500, blank=True)
    usuario = models.CharField(
        'Usuario',  max_length=100, blank=True)
    fecha = models.DateField('Fecha', blank=True)
    is_success = models.BooleanField('Exito', blank=True, default=False)

    class Meta:
        verbose_name = 'Registro_Civil'
        verbose_name_plural = 'Registro_Civil'
        ordering = ['busqueda']

    def __str__(self):
        return self.busqueda
        
        

class Contacto(models.Model):
    """ Model Contacto """

    rfc = models.ForeignKey(REC, on_delete=models.CASCADE)
    programa_id = models.ForeignKey(Programa, on_delete=models.CASCADE, blank=True, null=True)
    correo = models.EmailField('Correo', max_length=100, blank=True, null=True)
    telefono = models.CharField('Telefono', max_length=20, blank=True, null=True)
    ext = models.CharField('Extension', max_length=10, blank=True, null=True)
    fecha_alta = models.DateField('Fecha', blank=True, null=True)
    nombre = models.CharField('Contacto', max_length=254, blank=True, null=True)
    puesto = models.CharField('Puesto', max_length=254, blank=True, null=True)
    direccion = models.CharField('Direccion', max_length=254, blank=True, null=True)
    imagen = models.ImageField('Imagen', upload_to='media/contacto', blank=True, null=True)
    coordenada = models.CharField('Coordenada', max_length=60, blank=True, null=True)
    visible = models.BooleanField(blank=True, null=True, default=False)
    actualizado = models.BooleanField(blank=True, null=True, default=False)
    usuario = models.CharField('Usuario',  max_length=100, blank=True, null=True)
    is_active = models.BooleanField('Activo', default=True)

    objects = ContactoManager()

    def save(self, *args, **kwargs):
        if self.imagen:
            base_dir = settings.MEDIA_ROOT + '/media/contacto/'
            path = os.path.join(base_dir, str(self.imagen))
            lat, long = get_exif_location(get_exif_data(path))

            if lat == None:
                lat = '-'

            if long == None:
                long = '-'

            self.coordenada = str(lat) + ',' + str(long)
        
        super(Contacto, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Contacto'
        ordering = ['rfc']
        
    def __str__(self):
        return str(self.rfc)


class BP(models.Model):
    """ Model Obligaciones """

    rfc = models.ForeignKey(REC, on_delete=models.CASCADE)
    parter = models.CharField('Parter', max_length=50, blank=True, null=True)
    
    class Meta:
        verbose_name = 'BP'
        verbose_name_plural = 'BP'
        ordering = ['rfc']
        
    def __str__(self):
        return str(self.rfc)


class Obligaciones(models.Model):
    """ Model Obligaciones """

    rfc = models.ForeignKey(REC, on_delete=models.CASCADE)
    obligacion = models.CharField('Obligacion', max_length=254, blank=True, null=True)
    fecha_alta = models.DateField('Fecha Alta', blank=True, null=True)
    estatus = models.CharField('Estatus', max_length=50, blank=True, null=True)
    objeto = models.CharField('Objeto', max_length=50, blank=True, null=True)
    fecha_bloqueo = models.DateField('Fecha Bloqueo', blank=True, null=True)
    oc = models.CharField('OC', max_length=50, blank=True, null=True)

    class Meta:
        verbose_name = 'Obligaciones'
        verbose_name_plural = 'Obligaciones'
        ordering = ['rfc']
        
    def __str__(self):
        return str(self.rfc)


class Cartas_Invitacion(models.Model):
    """ Model Cartas Invitacion """

    folio = models.CharField('Folio', max_length=50, blank=True)
    rfc = models.CharField('RFC', max_length=30, blank=True)
    programa = models.CharField(
        'Programa', max_length=50, blank=True, null=True)
    resultado = models.CharField(
        'Nombre', max_length=300, blank=True, null=True)
    fecha_envio = models.DateField('Fecha', blank=True, null=True)
    estatus = models.CharField('Estatus', max_length=50, blank=True, null=True)
    usuario = models.CharField(
        'Usuario',  max_length=100, blank=True, null=True)
    remesa = models.CharField(
        'Remesa',  max_length=100, blank=True, null=True)


class Circulo_Credito(TimeStampedModel):
    # Model Círculo Crédito
    rfc = models.CharField("RFC", max_length=13, null=True, blank=True)
    tipo_persona = models.CharField("Tipo Persona", max_length=1, null=True, blank=True)
    numero_cuenta = models.CharField("Número Cuenta", max_length=255, null=True, blank=True)
    razon_social = models.CharField("Razón Social", max_length=200, null=True, blank=True)
    nombre = models.CharField("Nombre", max_length=250, null=True, blank=True)
    apellido_paterno = models.CharField("Apellido Paterno", max_length=250, null=True, blank=True)
    apellido_materno = models.CharField("Apellido Materno", max_length=250, null=True, blank=True)
    curp = models.CharField("CURP", max_length=18, null=True, blank=True)
    fecha_nacimiento = models.DateField("Fecha Nacimiento / Constitución", null=True, blank=True)
    sexo = models.CharField("Sexo", max_length=1, null=True, blank=True)
    nacionalidad = models.CharField("Nacionalidad", max_length=2, null=True, blank=True)
    calle = models.CharField("Calle", max_length=255, null=True, blank=True)
    numero_ext = models.CharField("Numero ext", max_length=30, null=True, blank=True)
    numero_int = models.CharField("Numero int", max_length=30, null=True, blank=True)
    colonia = models.CharField("Colonia", max_length=255, null=True, blank=True)
    municipio = models.CharField("Municipio", max_length=255, null=True, blank=True)
    ciudad = models.CharField("Ciudad", max_length=255, null=True, blank=True)
    estado = models.CharField("Estado", max_length=25, null=True, blank=True)
    cp = models.CharField("Codigo Postal", max_length=5, null=True, blank=True)
    telefono = models.CharField("Telefono", max_length=20, null=True, blank=True)
    adeudo = models.DecimalField("Adeudo", max_digits=15, decimal_places=2, null=True, blank=True)
    fecha_alta = models.DateField("Fecha Alta", null=True, blank=True)
    fecha_ultimo_pago = models.DateField("Fecha Último Pago", null=True, blank=True)
    correo = models.CharField("Correo Electrónico", max_length=250, null=True, blank=True)
    interlocutor = models.CharField("Interlocutor", max_length=50, null=True, blank=True)
    objeto_contrato = models.CharField("Objeto Contrato", max_length=50, null=True, blank=True)
    clave = models.CharField("Clave", max_length=4, null=True, blank=True)
    sub_clave = models.CharField("Sub Clave", max_length=4, null=True, blank=True)
    importe_baja = models.DecimalField("Importe Baja", max_digits=15, decimal_places=2, null=True, blank=True)
    periodo = models.IntegerField("Periodo", default=0)
    ejercicio = models.IntegerField("Ejercicio", default=0)
    usuario = models.CharField("Usuario", max_length=100, null=True, blank=True)
    area = models.CharField("Área", max_length=200, null=True, blank=True)
    is_active = models.BooleanField('Activo', default=True)
    descripcion = models.CharField("Descripcion", max_length=500, null=True, blank=True)

    class Meta:
        verbose_name = "circulo_credito"

templates/programacion/consulta/old/ver_autorizacion.html
{% load tags %}
{% load permissions %}
{% load l10n %}
{% load humanize %}
<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h6>Detalle</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

            <div class="modal-body">
                <label>{{id}}</label>
                <div class="form-row">
                    
                    <div class="form-group col-md-4">
                        <label><strong>RFC:</strong></label>
                        <label>{{ detail.rfc }}</label>
                    </div>
                    <div class="form-group col-md-4">
                        <label><strong>Programa:</strong></label>
                        <label>{{ detail.programa }}</label>
                    </div>
                    <div class="form-group col-md-4">
                        <label><strong>Presuntiva:</strong></label>
                        <strong><label class="text-success">$ {{ detail.presuntiva|unlocalize|intcomma }}</label></strong>
                    </div>
                </div>
                    <div class="form-group">
                        <label><strong>Nombre:</strong></label>
                        <label>{{ detail.nombre }}</label>
                    </div>
                    <div class="form-group">
                        <label><strong>Direccion:</strong></label>
                        <label>{{ detail.direccion }}</label>
                    </div>

                <br>
               
                <div class="tab round shadow">
                    <ul class="nav nav-tabs" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active show" id="home-08-tab" data-toggle="tab" href="#home-08"
                                role="tab" aria-controls="home-08" aria-selected="true"> <i class="fa fa-list-ul"></i>
                                Seguimiento </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-08-tab" data-toggle="tab" href="#profile-08" role="tab"
                                aria-controls="profile-08" aria-selected="false"><i class="fa fa-file"></i> Archivos
                            </a>
                        </li>
                    </ul>

                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="home-08" role="tabpanel" aria-labelledby="home-08-tab">
                            <div class="table-responsive mt-15">
                                <table class="table center-aligned-table mb-0">
                                    <thead>
                                        <tr class="text-dark">
                                            <th>Fecha</th>
                                            <th>Comentarios</th>
                                            <th>Estatus</th>
                                            <th>Autorizacion</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for detalle in detalles %}
                                        <tr>
                                            <td>{{ detalle.fecha|date:'d/m/Y' }}</td>
                                            <td>
												{% if detalle.comentarios != None %}
													{{ detalle.comentarios }}
												{% endif %}
											</td>
                                            <td>{{ detalle.estatus }}</td>
                                            <td>
                                                {% if detalle.usuario != None %}
                                                    {% get_user_info detalle.usuario %}
                                                {% endif %}
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>

                        <div class="tab-pane fade" id="profile-08" role="tabpanel" aria-labelledby="profile-08-tab">
                            <div class="table-responsive mt-15">
                                <table class="table center-aligned-table mb-0">
                                    <thead>
                                        <tr>
                                            <th>Fecha</th>
                                            <th>Tipo</th>
                                            <th>Comentarios</th>
                                            <th>Archivo</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
									
										{% has_perms request.user 'change_archivos' as change_archivos %}
										{% has_perms request.user 'delete_archivos' as delete_archivos %}
										
                                        {% for archivo in archivos %}
                                        <tr>
                                            <td>{{ archivo.fecha|date:'d/m/Y' }}</td>
                                            <td>{{ archivo.tipo }}</td>
                                            <td>{{ archivo.comentarios }}</td>
                                            <td>
                                                <a href="{{ archivo.archivo.url }}" class="btn btn-primary btn-sm" target="_blank"><i class="ti-file"></i></a>
                                            </td>
                                            <td>
												{% if change_archivos is True %}
                                                <button id="btUpdate_File" onclick="Update_Files('{% url 'programacion_app:editar-archivo' archivo.id %}', '{{archivo.id}}', '')" 
                                                    data-toggle="tooltip" data-placement="top" title="Editar" 
                                                    class="btn btn-warning btn-sm" target="_blank">
                                                    <i class="fa fa-pencil"></i>
                                                </button>
												{% endif %}
												{% if delete_archivos is True %}
												{% csrf_token %}
                                                <button id="btDelete_File" onclick="Delete_File('{% url 'programacion_app:eliminar-archivo' archivo.id %}', '{{archivo.id}}')" 
                                                    data-toggle="tooltip" data-placement="top" title="Eliminar" 
                                                    class="btn btn-danger btn-sm" target="_blank">
                                                    <i class="fa fa-times"></i>
                                                </button>
												{% endif %}
                                            </td>
                                        </tr>   
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>



               
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>

    </div>
</div>

<div class="modal fade" id="mdUpdate_Files" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
</div>

<div class="modal fade" id="mdDelete_Files" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
</div>

{% block extrajs %}
<script>
    $(document).ready(function () {

        $('.alert-success').fadeOut(6000);

    });

    function Update_Files(myURL, myID, myFolio) {
        $('#mdUpdate_Files').load(myURL, function () {

            $("#id_programa_id option[value='" + myID + "']").attr('selected', 'selected');
            $("#id_programa_id").hide();

            $('#tbOficio3').prop('readonly', 'readonly');
            $('#tbOficio3').val(myID);

            var value = $('#hfType').val();
            $("#id_tipo option[value='" + value + "']").attr('selected','selected');

            $('.date-picker-default').datepicker({
                format: 'dd/mm/yyyy'
            });
            $('.date-picker-default').css("background-color", "#f6f7f8");

            $(this).modal('show');
        });
    }
	
		
	  function Delete_File(myURL, myID){

        swal({
            title: 'Seguro que desea eliminar?',
            text: "este Archivo!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Confirmar',
            cancelButtonText: 'Cancelar',
            confirmButtonClass: 'btn btn-danger',
            cancelButtonClass: 'btn btn-secondary',
            buttonsStyling: false,
            reverseButtons: true
        }).then((result) => {
            if (result.value) {

                $.ajax({
                    data: {
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                    },
                    url: myURL,
                    type: "POST",
                    success: function (response) {

                        console.log(response);
                        location.reload();  
                    },
                    error: function (error) {

                        console.log(error);
                    }
            });

                swal(
                'Eliminado!',
                'Exitosamente.',
                'success'
                )
            } else if (
                // Read more about handling dismissals
                result.dismiss === swal.DismissReason.cancel
            ) {
                swal(
                'Cancelado',
                '',
                'error'
                )
            }
        })

       

    }

</script>
{% endblock extrajs %}

templates/programacion/consulta/old/ver_contribuyente.html
<h1>get contribuyente</h1>

<table id="datatable1" class="table table-striped table-bordered p-0">
    <thead>
        <tr>
            <th>
                <input type="checkbox" name="select_all" value="1" id="example-select-all">
            </th>
            <th>Oficio</th>
            <th>RFC</th>
            <th>Nombre</th>
            <th>Programa</th>
            <th>Fecha Creación</th>
            <th>Etapa</th>
            <th>Detalle</th>
        </tr>
    </thead>
    <tbody>
        {% for programa in programacion %}
        <tr>
            <td> {{ programa.id}} </td>
            <td>
                <a href="{% url 'programacion_app:admin-programacion' programa.id %}" class="btn btn-link" target="_blank">{{ programa.folio }}</a>
            </td>
            <td>{{ programa.rfc }}</td>
            <td>{{ programa.nombre }}</td>
            <td>{{ programa.programa }}</td>                                
            <td><span class="sp_date">{{ programa.fecha|date:'Y/m/d' }}</span> {{ programa.fecha|date:'d/m/Y' }}</td>
            <td>
                {{ programa.estatus }}
            </td>
            <td>
                <button id="btUpdate" onclick="Update_Modal('{% url 'programacion_app:editar-contribuyente' programa.id %}')" data-toggle="tooltip" data-placement="top" title="Editar" class="btn btn-warning btn-sm" target="_blank"><i class="fa fa-pencil"></i> </button>

                <button id="btDetail" onclick="View_Modal('{% url 'programacion_app:ver-todo' programa.id %}')" data-toggle="tooltip" data-placement="top" title="Detalle" class="btn btn-warning btn-sm" target="_blank"><i class="fa fa-list-ul"></i> </button>

            </td>
        </tr>   
        {% endfor %}
    </tbody>

</table>