Recaudacion/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.views.generic import TemplateView
from applications.home.views import Error404View, Error505View
from .routers import router


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('allauth.urls')),
    
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.oficios.urls')),
    re_path('', include('applications.programacion.urls')),
    re_path('', include('applications.rec.urls')),
    re_path('', include('applications.padrones.urls')),
    re_path('', include('applications.transferidos.urls')),
    re_path('', include('applications.promocion.urls')),
    re_path('', include('applications.direccion.urls')),
    re_path('', include('applications.juridico.urls')),
    re_path('', include('applications.quinielas.urls')),
    re_path('', include('applications.saladejuntas.urls')),
    re_path('', include('applications.tramites.urls')),
    re_path('', include('applications.verificacion_vehicular.urls')),
    
    path('api/', include(router.urls)),
    path('modelos/', TemplateView.as_view(template_name='programacion/modelos.html')),
    re_path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = Error404View.as_view()
handler500 = Error505View.as_error_view()

applications/transferidos/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from . import functions

app_name = "transferidos_app"

urlpatterns = [
    path('lista-transferencias/', views.Lista_Transferencias.as_view(),
         name='lista-transferencias'),
    path('activos-auditoria/', views.Activos_Auditoria.as_view(),
         name='activos-auditoria'),
    path('activos-ejecucion/', views.Activos_Ejecucion.as_view(),
         name='activos-ejecucion'),
    path('admin-transferencias/<str:folio>/', views.Admin_Transferencias.as_view(),
         name='admin-transferencias'),
    path('rechazar/<str:folio>/', views.Rechazar.as_view(),
         name='rechazar'),
    path('aceptar/', views.Aceptar.as_view(),
         name='aceptar'),
    path('opcion/', views.Opcion.as_view(),
         name='opcion'),
    path('lista-auditoria/', views.Lista_Auditoria.as_view(),
         name='lista-auditoria'),
    path('lista-ejecucion/', views.Lista_Ejecucion.as_view(),
         name='lista-ejecucion'),
    path('admin-areas/<str:folio>/', views.Admin_Areas.as_view(),
         name='admin-areas'),
    path('alta-transferencia/', views.Alta_Transferencia.as_view(),
         name="alta-transferencia"),
    path('alta-contribuyente-2/', views.Alta_Contribuyente2.as_view(),
         name='alta-contribuyente-2'),
    path('editar-contribuyente-2/<int:pk>/', views.Editar_Contribuyente.as_view(), name='editar-contribuyente-2'),
    path('consulta-auditoria/', views.Consulta.as_view(), name='consulta-auditoria'),
    path('consulta-ejecucion/', views.Consulta.as_view(), name='consulta-ejecucion'),
    
    
    path('admin-programacion-3/<id>/', views.Admin_Programacion.as_view(), name='admin-programacion-3'),
    path('lista-programacion-auditoria/', views.Lista_Programacion_Auditoria.as_view(), name='lista-programacion-auditoria'),
    path('lista-programacion-ejecucion/', views.Lista_Programacion_Ejecucion.as_view(), name='lista-programacion-ejecucion'),
    path('solicitudes-apoyo/', views.Solicitudes_Apoyo.as_view(), name='solicitudes-apoyo'),
    
    path('ver-reporte-3/<int:pk>/', views.Ver_Reporte.as_view(), name='ver-reporte-3'),
    
    path('alta-detalle-3/<int:pk>/', views.Alta_Detalle.as_view(), name='alta-detalle-3'),    
    path('alta-archivos-3/<int:pk>/', views.Alta_Archivos.as_view(), name='alta-archivos-3'),
    path('alta-pagos-3/<int:pk>/', views.Alta_Pagos.as_view(), name='alta-pagos-3'),
    path('editar-pago-3/<int:pk>/', views.Editar_Pago.as_view(), name='editar-pago-3'),
    path('editar-detalle-3/<int:pk>/', views.Editar_Detalle.as_view(), name='editar-detalle-3'),
    path('editar-archivo-3/<int:pk>/', views.Editar_Archivo.as_view(), name='editar-archivo-3'),
    path('ver-todo-3/<int:pk>/', views.Ver_Todo.as_view(), name='ver-todo-3'),
    path('eliminar-detalle-3/<int:pk>/', views.Eliminar_Detalle.as_view(), name='eliminar-detalle-3'),
    path('eliminar-pago-3/<int:pk>/', views.Eliminar_Pagos.as_view(), name='eliminar-pago-3'),
    path('eliminar-archivo-3/<int:pk>/', views.Eliminar_Archivos.as_view(), name='eliminar-archivo-3'),
    path('get-contribuyente-2/<rfc>/', views.Get_Contribuyente2.as_view(), name='get-contribuyente-2'),
    
    path('get-data/<rfc>/', views.Get_Data.as_view(), name='get-data'),
    path('get-no-control/<rfc>/', views.Get_NoControl.as_view(), name='get-no-control'),

    
    path('aceptar-todos/', views.Aceptar_Todos.as_view(),
         name='aceptar-todos'),
    path('rechazar-todos/', views.Rechazar_Todos.as_view(),
         name='rechazar-todos'),
    path('asignar-auditoria/', views.Asignar_Auditoria.as_view(), name='asignar-auditoria'),
    path('asignar-solicitud/', views.Asignar_Solicitud.as_view(), name='asignar-solicitud'),

    path('alta-ejecucion/', views.Alta_Ejecucion.as_view(), name='alta-ejecucion'),
    path('editar-ejecucion/<int:pk>/', views.Editar_Ejecucion.as_view(), name='editar-ejecucion'),
    
    path('concluidos-ejecucion/', views.Concluidos_Ejecucion.as_view(), name='concluidos-ejecucion'),
    path('seguimiento-ejecucion/', views.Seguimiento_Ejecucion.as_view(), name='seguimiento-ejecucion'),

    path('concluidos-auditoria/', views.Concluidos_Auditoria.as_view(), name='concluidos-auditoria'),
    path('seguimiento-auditoria/', views.Seguimiento_Auditoria.as_view(), name='seguimiento-auditoria'),
    path('fecha-cierre/<int:pk>/', views.Fecha_Cierre.as_view(), name='fecha-cierre'),

    path('batch/', views.Batch_Ejecucion.as_view(), name='batch'),
    path('excel-ejecucion/<str:archivo>/', views.DescargarExcel, name='excel-ejecucion'),
    path('excel-activos-auditoria/', functions.activos_auditoria, name='excel-activos-auditoria'),
    path('excel-activos-ejecucion/', functions.activos_ejecucion, name='excel-activos-auditoria'),

    path('impuestos-transferidos/<int:pk>/', views.ImpuestosView.as_view(), name='impuestos-transferidos'),
    path('limpiar-impuestos/', views.LimpiarImpuestos.as_view(), name='limpiar-impuestos'),
    path('ver-impuestos-transferidos/<int:rfc>/', views.Ver_Impuestos.as_view(), name='ver-impuestos-transferidos'),

    path('admin-impuestos-transferidos/<str:rfc>/<str:impuesto>/', views.Admin_Impuestos.as_view(), name='admin-impuestos-transferidos'),
]

applications/transferidos/views.py
import datetime
import csv
import os
import json
import ast
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.base import View
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView
)
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic.edit import DeleteView, FormView
from django.db.models import Q, OuterRef, Subquery, Count, Sum, CharField, Value, F, DurationField, ExpressionWrapper
from django.db.models.functions import Concat, ExtractDay
from django.contrib.postgres.aggregates.general import ArrayAgg
from applications.rec.models import Contacto, REC, Busquedas, Fiscalizados, Cartas_Invitacion
from applications.home.models import Codigos_Maestros
from applications.users.models import User
from applications.programacion.models import Programa, Detalle
from applications.padrones.models import Programa_Padrones
from django.conf import settings
from django.db import transaction

from .models import Programa_Transferidos, Detalle_Transferidos, Pagos_Transferidos, Archivos_Transferidos, Temporal, Impuestos
from .forms import (
    RechazarForm, 
    AceptarForm, 
    TransferenciaForm, 
    OpcionForm, 
    ContribuyenteForm, 
    ArchivosForm, 
    DetalleForm, 
    PagosForm, 
    RechazarTodosForm, 
    AceptarTodosForm,
    AsignarAuditoriaForm,
    ContribuyenteEjecucionForm,
    BatchForm,
    FechaCierreForm,
    ImpuestosForm
)
from django.db import connection
from applications.users.mixins import GlobalMixin, CRUDMixin


# ============================= ListView ================================================ #
class Lista_Transferencias(GlobalMixin, ListView):
    template_name = 'transferidos/lista_transferencias.html'
    model = Programa_Transferidos
    context_object_name = 'propuestas'

    def get_queryset(self):

        estatus = Detalle.objects.filter(
            programa_id=OuterRef('pk'),
            estatus__in=['NO LOCALIZADO','NEGACION DE AUTOCORRECION'],
            is_active=True
        ).order_by('-fecha')

        transferir_ejecucion = Detalle.objects.filter(
            programa_id=OuterRef('pk'),
            estatus__in=['PARA TRANSFERIR'],
            comentarios__icontains = '[Se propone transferencia a EJECUCIÓN]',
            is_active=True
        ).order_by('-fecha')

        autorizacion = Detalle.objects.filter(
            programa_id=OuterRef('pk'),
            estatus='OFICIO'
        ).order_by('-fecha')

        queryset = Programa.objects.filter(
            estatus='PROPUESTA TRANSFERENCIA'
        ).annotate(
            estatus_cierre=Subquery(estatus.values('estatus')[:1]),
            transferir_ejecucion=Subquery(transferir_ejecucion.values('comentarios')[:1]),
            fecha_autorizacion=Subquery(autorizacion.values('fecha')[:1])
        )

        # queryset = Programa_Transferidos.objects.filter(
        #     ~Q(nuevo_folio=''),
        #     is_active=False,
        #     estatus='TRANSFERIDO'
        # ).values(
        #     'nuevo_folio', 'area', 'fecha'
        # ).annotate(
        #     sum_rfc=Count('rfc'),
        #     sum_presuntiva=Sum('presuntiva')
        # ).order_by()

        return queryset

    def get_context_data(self, **kwargs):
        context = super(Lista_Transferencias, self).get_context_data(**kwargs)

        context['transferencias'] = Programa_Transferidos.objects.filter(
            # area = 'AUDITORIA',
            is_active=True,
            estatus='TRANSFERIDO'
           
        )

        context['aceptadas'] = Programa_Transferidos.objects.filter(
            #~Q(nuevo_folio=''),
            # area='AUDITORIA',
            is_active=True,
            estatus__in= ['ACEPTADO','CONCLUIDO' ],
            usuario='gcisnerosg'
        )

        context['rechazadas'] = Programa_Transferidos.objects.filter(
            # area='AUDITORIA',
            is_active=True,
            estatus='RECHAZADO'
        )


        # queryset = Programa_Transferidos.objects.filter(
        #     ~Q(nuevo_folio=''),
        #     is_active=True,
        #     etapa__in=['CIERRE','TRANSFERIDO','NUEVO','SEGUIMIENTO']
        # ).values(
        #     'nuevo_folio', 'area'
        # ).annotate(
        #     sum_rfc=Count('rfc'),
        #     sum_presuntiva=Sum('presuntiva'),
        #     sum_transferidos=Sum(
        #         Case(
        #             When(estatus='TRANSFERIDO', then=1), default=0, output_field=IntegerField()
        #         )
        #     ),
        #     sum_rechazados=Sum(
        #         Case(
        #             When(estatus='RECHAZADO', then=1), default=0, output_field=IntegerField()
        #         )
        #     ),
        #     sum_nuevos=Sum(
        #         Case(
        #             When(estatus='NUEVO', then=1), default=0, output_field=IntegerField()
        #         )
        #     )
        # ).order_by()
        # context['enviados'] = queryset

        return context


class Admin_Areas(LoginRequiredMixin, ListView):
    template_name = 'transferidos/admin_areas.html'
    context_object_name = 'transferidos'

    def get_queryset(self):
        start = self.kwargs.get('folio')[:-5]
        end = self.kwargs.get('folio')[-5:].replace('-', '/')
        nuevo_folio = self.kwargs.get('folio')

        if Programa_Transferidos.objects.filter(nuevo_folio=nuevo_folio, is_active=True).exists():
            queryset = Programa_Transferidos.objects.filter(
                nuevo_folio=nuevo_folio,
                is_active=True,
                estatus='TRANSFERIDO'
            )
        else:
            queryset = None

        return queryset

    def get_context_data(self, **kwargs):
        context = super(Admin_Areas, self).get_context_data(**kwargs)

        start = self.kwargs.get('folio')[:-5]
        end = self.kwargs.get('folio')[-5:].replace('-', '/')
        nuevo_folio = self.kwargs.get('folio')

        context['folio'] = nuevo_folio

        if Programa_Transferidos.objects.filter(
                nuevo_folio=nuevo_folio, is_active=True).exists():
            obj = Programa_Transferidos.objects.filter(
                nuevo_folio=nuevo_folio, is_active=True)[:1]
            area = str(obj[0].area)
        else:
            area = 'Sin contribuyentes'

        context['area'] = area

        return context


class Admin_Transferencias(LoginRequiredMixin, ListView):
    template_name = 'transferidos/admin_transferencias.html'
    context_object_name = 'transferidos'

    def get_queryset(self):
        nuevo_folio = self.kwargs.get('folio')

        if Programa_Transferidos.objects.filter(nuevo_folio=nuevo_folio).exists():
            queryset = Programa_Transferidos.objects.filter(
                nuevo_folio=nuevo_folio)
        else:
            queryset = None

        return queryset

    def get_context_data(self, **kwargs):
        context = super(Admin_Transferencias, self).get_context_data(**kwargs)

        nuevo_folio = self.kwargs.get('folio')

        context['folio'] = nuevo_folio

        if Programa_Transferidos.objects.filter(
                nuevo_folio=nuevo_folio).exists():
            obj = Programa_Transferidos.objects.filter(
                nuevo_folio=nuevo_folio)
            area = str(obj[0].area)
        else:
            area = 'Sin contribuyentes'

        context['area'] = area

        return context


class Aceptar(LoginRequiredMixin, FormView):
    template_name = "transferidos/aceptar.html"
    form_class = AceptarForm
    success_message = "aceptado correctamente!"

    def form_valid(self, form):

        id = form.cleaned_data['folio']

        obj = Programa_Transferidos.objects.get(id=id)
        obj.estatus = 'ACEPTADO'
        obj.save()

        Detalle_Transferidos.objects.create(
            programa_id=obj,
            fecha=datetime.date.today(),
            comentarios='',
            estatus='ACEPTADO',
            usuario=self.request.user.username
        )

        # query = Programa_Transferidos.objects.filter(
        #     nuevo_folio=folio,
        #     is_active=False
        # )

        # for row in query:
        #     obj = Programa.objects.get(folio=row.folio)
        #     obj.estatus = 'CONCLUIDO'
        #     obj.save()

        #     Detalle.objects.create(
        #         programa_id=obj,
        #         fecha=datetime.date.today(),
        #         comentarios='',
        #         estatus='CONCLUIDO',
        #         usuario=self.request.user.username
        #     )

        # Programa_Transferidos.objects.filter(
        #     nuevo_folio=folio
        # ).update(
        #     is_active=True,
        #     fecha=datetime.date.today()
        # )

        return super(Aceptar, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('transferidos_app:lista-transferencias')


class Opcion(LoginRequiredMixin, FormView):
    template_name = "transferidos/opcion.html"
    form_class = OpcionForm
    success_message = "Guardado correctamente!"

    # def get_context_data(self, **kwargs):
    #     context = super(Opcion, self).get_context_data(**kwargs)

    #     context['no_control'] = self.kwargs.get('no_control')
    #     return context

    def form_valid(self, form):

        id = form.cleaned_data['lista']

        if form.cleaned_data['comentarios']:
            cmmt = form.cleaned_data['comentarios']
        else:
            cmmt = ''

        if form.cleaned_data['opcion'] == 'ACEPTAR':
            obj = Programa_Transferidos.objects.get(id=id)
            obj.estatus = 'ACEPTADO'
            obj.metodo_envio = str(form.cleaned_data['metodo_envio'])

templates/transferidos/consulta/consulta_rfc.html
{% load tags %}
{% load l10n %}
{% load humanize %}
<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h6>Consulta</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form action="{% url 'transferidos_app:ver-todo-3' 34 %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="modal-body">
                <label>{{id}}</label>
                <div class="form-row">
                    
                    <div class="form-group col-md-6">
                        <label><strong>RFC:</strong></label>
                        <label>{{ detail.rfc }}</label>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label><strong>Nombre:</strong></label>
                        <label>{{ detail.nombre }}</label>
                    </div>
                    <div class="form-group col-md-6">
                        <label><strong>Direccion:</strong></label>
                        <label>{{ detail.direccion }}</label>
                    </div>

                </div>
               
				<div class="table-responsive">
                    
                    <table id="table" class="table table-striped table-bordered p-0">
                        <thead>
                            <tr>
                                <th>RFC</th>
                                <th>Nombre</th>
                                <th>Direccion</th>
                                <th>Estatus</th>
                                <th>Programas</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for rec in contribuyentes %}
                            <tr>
                                <td>{{ rec.rfc }}</td>
                                <td>{{ rec.nombre }}</td>
                                <td>{{ rec.direccion }}</td>
                                <td>
                                   {% if det1 or det2 or det3 or det4 %}
                                    <div class="text-center">
                                        <span class="badge badge-pill badge-success">ACTIVO</span>
                                    </div>
                                   {% endif %}
                                </td>
                                <td>
                                    {% for detalle in det1 %}
                                        <span class="badge badge-pill badge-primary">{{ detalle.programa }} / RECAUDACION</span>
                                    {% endfor %}
                                    {% for detalle in det2 %}
                                        <span class="badge badge-pill badge-primary">{{ detalle.programa }} / RECAUDACION</span> 
                                    {% endfor %}
									{% for detalle in det3 %}
                                        <span class="badge badge-pill badge-primary">{{ detalle.programa }} / AUDITORIA</span>
                                    {% endfor %}
                                    {% for detalle in det4 %}
                                        <span class="badge badge-pill badge-primary">{{ detalle.programa }} / EJECUCION</span> 
                                    {% endfor %}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    
                    </table>
                </div>



               
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
            </div>

        </form>
    </div>
</div>

templates/transferidos/consulta/general.html
{% extends 'base_new.html' %}
{% load static %}
{% load tags %}

{% block title %} Consulta {% endblock title %}


{% block content %}
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
            </div>
            <h4 class="page-title">Consulta</h4>  
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-8 mb-30">
        <div class="card">
            <div class="card-body">

                <form method="GET">
                    <div class="input-group">

                        <span class="input-group-text">Contribuyente</span>
                        <input type="text" class="form-control" id="kword" name="kword" placeholder="RFC o Nombre...">

                        <button type="submit" class="btn btn-primary btn" target="_blank" value="Buscar"> <i
                                class="fa fa-search"></i> Buscar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xl-12 mb-30">
        <div class="card">
            <div class="card-body">
                {% if paramertro %}
                    <div class="table-responsive">
                        <table id="table" class="table table-striped table-bordered p-0">
                            <thead>
                                <tr>
                                    <th>RFC</th>
                                    <th>Nombre</th>
                                    <th>Direccion</th>
                                    <th>Estatus</th>
                                    <th>Programas</th> 
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    {% for rec in contribuyentes %}
                                    <td>{{ rec.rfc }}</td>
                                    <td>{{ rec.nombre }}</td>
                                    <td>{{ rec.direccion }}</td>
                                    {% empty %}
                                        {% if det1 %}
                                            {% for detalle in det1 %}
                                            <td>{{ detalle.rfc }}</td>
                                            <td>{{ detalle.nombre }}</td>
                                            <td>{{ detalle.direccion }}</td>
                                            {% endfor %}
                                        {% else %}
                                            {% if det2 %}
                                                {% for detalle in det2 %}
                                                <td>{{ detalle.rfc }}</td>
                                                <td>{{ detalle.nombre }}</td>
                                                <td>{{ detalle.direccion }}</td>
                                                {% endfor %}
                                            {% else %}
                                                {% if det3 %}
                                                    {% for detalle in det3 %}
                                                    <td>{{ detalle.rfc }}</td>
                                                    <td>{{ detalle.nombre }}</td>
                                                    <td>{{ detalle.direccion }}</td>
                                                    {% endfor %}
                                                {% else %}
                                                    {% if det4 %}
                                                        {% for detalle in det4 %}
                                                        <td>{{ detalle.rfc }}</td>
                                                        <td>{{ detalle.nombre }}</td>
                                                        <td>{{ detalle.direccion }}</td>
                                                        {% endfor %}
                                                    {% else %}
                                                        {% if det5 %}
                                                            {% for detalle in det5 %}
                                                            <td>{{ detalle.rfc }}</td>
                                                            <td>{{ detalle.nombre }}</td>
                                                            <td>{{ detalle.direccion }}</td>
                                                            {% endfor %}
                                                        {% endif %}
                                                    {% endif %}
                                                {% endif %}
                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                    <td>
                                        <h5>
                                    {% if det1 or det2 or det3 or det4%}
                                        <div class="text-center">
                                            <span class="badge bg-success">ACTIVO</span>
                                        </div>
                                    {% endif %}
                                    
                                    {% for detalle in det5 %}
                                            <span class="badge bg-success">EN TRANSFERENCIA / {{ detalle.nuevo_folio }}</span> 
                                        {% endfor %}
                                    </h5>
                                    </td>
                                    <td>
                                        <h5>
                                        {% for detalle in det1 %}
                                            <span class="badge bg-primary">{{ detalle.programa }} / RECAUDACION</span>
                                        {% endfor %}
                                        {% for detalle in det2 %}
                                            <span class="badge bg-primary">{{ detalle.programa }} / RECAUDACION</span> 
                                        {% endfor %}
                                        {% for detalle in det3 %}
                                            <span class="badge bg-primary">{{ detalle.programa }} / AUDITORIA</span>
                                        {% endfor %}
                                        {% for detalle in det4 %}
                                            <span class="badge bg-primary">{{ detalle.programa }} / EJECUCION</span> 
                                        {% endfor %}
                                        </h5>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        Ingrese el RFC o nombre del contribuyente a buscar...
                        </button>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content %}