Recaudacion/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500
from django.views.generic import TemplateView
from applications.home.views import Error404View, Error505View
from .routers import router


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('allauth.urls')),
    
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.oficios.urls')),
    re_path('', include('applications.programacion.urls')),
    re_path('', include('applications.rec.urls')),
    re_path('', include('applications.padrones.urls')),
    re_path('', include('applications.transferidos.urls')),
    re_path('', include('applications.promocion.urls')),
    re_path('', include('applications.direccion.urls')),
    re_path('', include('applications.juridico.urls')),
    re_path('', include('applications.quinielas.urls')),
    re_path('', include('applications.saladejuntas.urls')),
    re_path('', include('applications.tramites.urls')),
    re_path('', include('applications.verificacion_vehicular.urls')),
    
    path('api/', include(router.urls)),
    path('modelos/', TemplateView.as_view(template_name='programacion/modelos.html')),
    re_path('ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = Error404View.as_view()
handler500 = Error505View.as_error_view()

applications/promocion/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "promocion_app"

urlpatterns = [
    # urls Actualizaciones
    path(
        'actualizaciones/',
        views.Actualizaciones.as_view(),
        name='actualizaciones'
    ),
    path(
        'actualizaciones/admin/<int:id>/',
        views.Admin_Eventos.as_view(),
        name='actualizaciones-admin'
    ),
    path(
        'actualizaciones/admin/visita/<int:id>/',
        views.Detalle_Visita.as_view(),
        name='detalle-visita'
    ),
    path(
        'ver-tramites/<int:idVisita>/',
        views.Ver_Tramites.as_view(),
        name='ver-tramites'
    ),
    path(
        'todos-tramites/<str:rfc>/',
        views.Todos_Tramites.as_view(),
        name='todos-tramites'
    ),
    path(
        'alta-visita/<int:id>/',
        views.Alta_Visita.as_view(),
        name='alta-visita'
    ),
    path(
        'alta-visita-detalle/<int:idVisita>/<int:idActividad>',
        views.Alta_Detalle.as_view(),
        name='alta-visita-detalle'
    ),
    path(
        'guardar-visita-detalle/<int:idVisita>',
        views.Guardar_Detalle.as_view(),
        name='guardar-visita-detalle'
    ),
    path(
        'editar-visita/<int:pk>/<int:idDesarrollo>/',
        views.Editar_Visita.as_view(),
        name='editar-visita'
    ),
    path(
        'editar-visita-detalle/<int:folio>/<int:idActividad>/',
        views.Editar_Detalle.as_view(),
        name='editar-visita-detalle'
    ),
    path(
        'eliminar-visita/<int:pk>/',
        views.Eliminar_Visita.as_view(),
        name='eliminar-visita'
    ),
    path(
        'eliminar-visita-detalle/<int:folio>/',
        views.Eliminar_Detalle.as_view(),
        name='eliminar-visita-detalle'
    ),
    path(
        'validar-rfc/<int:idDesarrollo>/<str:rfc>/',
        views.Validar_RFC.as_view(),
        name='validar-rfc'
    ),
    path('ver-mercado/<int:id_mercado>', views.Ver_Mercado.as_view(), name='ver-mercado'),

    path('recorridos/', views.Recorridos.as_view(), name='recorridos'),
    path('eventos-promocion/', views.Eventos_Promocion.as_view(), name='eventos-promocion'),
    path('visitas/<int:id_evento>', views.Desarrollos.as_view(), name='visitas'),

    path('programas-promocion/', views.Programas.as_view(), name='programas-promocion'),
    path(
        'crear-programa/',
        views.Alta_Programa.as_view(),
        name='crear-programa'
    ),
    path(
        'crear-evento/',
        views.Alta_Evento.as_view(),
        name='crear-evento'
    ),
    path(
        'crear-desarrollo/',
        views.Alta_Desarrollo.as_view(),
        name='crear-desarrollo'
    ),
    path(
        'modificar-programa/<int:pk>/',
        views.Editar_Programa.as_view(),
        name='modificar-programa'
    ),
    path(
        'ver-programa/<int:pk>/',
        views.Ver_Programa.as_view(),
        name='ver-programa'
    ),
    path(
        'aprobar-programa/<int:pk>/',
        views.Aprobar_Programa.as_view(),
        name='aprobar-programa'
    ),
    path(
        'asignacion-promocion/',
        views.Lista_Promocion.as_view(),
        name='asignacion-promocion'
    ),
]

applications/promocion/views.py
import csv
from datetime import datetime
from applications.users.functions import get_username
from applications.users.mixins import CRUDMixin, GlobalMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http.response import JsonResponse
from django.http import HttpResponse
from django.shortcuts import redirect
from django.views.generic import (CreateView, DeleteView, ListView,
                                  TemplateView, UpdateView)
from django.db.models import Q, Sum, F, Case, Count, When
from django.db.models.fields import IntegerField
from django.db import connection

from .forms import DesarrolloForm, EventoForm, VisitaForm, ProgramaForm, AprobarForm
from .models import (Actividades, Desarrollo, Evento, Formulario, Opciones, Programa_Actualizaciones,
                     Visita, Visita_Detalle, Detalle)
from applications.padrones.models import Programa_Padrones
from applications.users.models import User
from applications.home.models import Codigos_Maestros

# ============================= Actualizaciones ========================================== #

class Programas(GlobalMixin, TemplateView):
    template_name = 'promocion/programas.html'

    def get_context_data(self, **kwargs):
        context = super(Programas, self).get_context_data(**kwargs)

        context['programas'] =  Programa_Actualizaciones.objects.all().exclude(estatus='CANCELADO')
        context['cancelados'] =  Programa_Actualizaciones.objects.filter(estatus='CANCELADO')

        return context


class Actualizaciones(GlobalMixin, ListView):
    template_name = 'promocion/actualizaciones/eventos.html'
    context_object_name = 'desarrollo'

    def get_queryset(self):
        QuerySet = Desarrollo.objects.filter(
            id_evento__id_programa__nombre__in=['MERCADOS','TIANGUIS'], 
            estatus='EN PROCESO'
        ).annotate(
            sum_rfc=Sum(
                Case(
                    When(visita_desarrollo__is_active=True, then=1), default=0, output_field=IntegerField()
                )
            )
        ).order_by('id')

        return QuerySet

class Recorridos(GlobalMixin, ListView):
    template_name = 'promocion/recorridos/eventos.html'
    context_object_name = 'desarrollo'

    def get_queryset(self):
        QuerySet = Desarrollo.objects.filter(
            id_evento__id_programa__nombre='RECORRIDOS', 
            estatus='EN PROCESO'
        ).annotate(
            sum_rfc=Sum(
                Case(
                    When(visita_desarrollo__is_active=True, then=1), default=0, output_field=IntegerField()
                )
            )
        ).order_by('id')

        return QuerySet


class Eventos_Promocion(GlobalMixin, ListView):
    template_name = 'promocion/eventos_promocion.html'
    context_object_name = 'eventos'

    def get_queryset(self):
        QuerySet = Evento.objects.all().annotate(sum_visitas=Count('desarrollo_evento')).order_by('nombre')

        return QuerySet


class Desarrollos(LoginRequiredMixin, ListView):
    template_name = 'promocion/desarrollos.html'
    context_object_name = 'desarrollo'

    def get_queryset(self):
        id_evento = self.kwargs.get('id_evento')

        QuerySet = Desarrollo.objects.filter(
            id_evento = id_evento
        ).annotate(
            sum_rfc=Sum(
                Case(
                    When(visita_desarrollo__is_active=True, then=1), default=0, output_field=IntegerField()
                )
            )
        ).order_by('id')

        return QuerySet



class Admin_Eventos(GlobalMixin, ListView):
    template_name = 'promocion/actualizaciones/admin_eventos.html'
    context_object_name = 'eventos'

    def get_queryset(self):
        id_evento = self.kwargs.get('id')
        return Desarrollo.objects.filter(id=id_evento)

    def get_context_data(self, **kwargs):
        context = super(Admin_Eventos, self).get_context_data(**kwargs)

        idDesarrollo = self.kwargs.get('id')

        context['idDesarrollo'] = idDesarrollo

        context['visitas'] = Visita.objects.contribuyentes_por_desarrollo(
            id_desarrollo=idDesarrollo,
            username=get_username(self)
        )

        return context


class Detalle_Visita(LoginRequiredMixin, ListView):
    template_name = 'promocion/actualizaciones/detalle_visita.html'
    context_object_name = 'visita'

    def get_instance(self):
        id_visita = self.kwargs.get('id')
        return Visita.objects.filter(id=id_visita)

    def get_queryset(self):
        return self.get_instance()

    def get_context_data(self, **kwargs):
        context = super(Detalle_Visita, self).get_context_data(**kwargs)

        id_visita = self.kwargs.get('id')

        instance = self.get_instance()
        context['idBack'] = instance[0].id_desarrollo.id

        context['EstatalCheckForm'] = Formulario.objects.tipo_formulario_1(
            tramite='ESTATAL'
        )
        context['EstatalForm'] = Formulario.objects.tipo_formulario_2(
            tramite='ESTATAL'
        )
        context['FederalCheckForm'] = Formulario.objects.tipo_formulario_1(
            tramite='FEDERAL'
        )
        context['FederalForm'] = Formulario.objects.tipo_formulario_2(
            tramite='FEDERAL'
        )

        context['tramites_federales'] = Visita_Detalle.objects.tramites_por_contribuyente(
            tramite='FEDERAL',
            idVisita=id_visita,
            usuario=get_username(self)
        )
        context['tramites_estatales'] = Visita_Detalle.objects.tramites_por_contribuyente(
            tramite='ESTATAL',
            idVisita=id_visita,
            usuario=get_username(self)
        )

        return context
        

class Ver_Tramites(LoginRequiredMixin, TemplateView):
    template_name = 'promocion/actualizaciones/consulta/ver_tramites.html'

    def get_context_data(self, **kwargs):
        context = super(Ver_Tramites, self).get_context_data(**kwargs)

        id_visita = self.kwargs.get('idVisita')

        context['ver_tramites_federales'] = Visita_Detalle.objects.tramites_por_contribuyente(
            tramite='FEDERAL',
            idVisita=id_visita,
            usuario=''
        ).order_by('folio')

        context['ver_tramites_estatales'] = Visita_Detalle.objects.tramites_por_contribuyente(
            tramite='ESTATAL',
            idVisita=id_visita,
            usuario=''
        ).order_by('folio')

        return context
        

class Todos_Tramites(LoginRequiredMixin, TemplateView):
    template_name = 'promocion/actualizaciones/consulta/todos_tramites.html'

    def get_context_data(self, **kwargs):
        context = super(Todos_Tramites, self).get_context_data(**kwargs)

        rfc = self.kwargs.get('rfc')

        context['tramites_federales'] = Visita_Detalle.objects.tramites_por_contribuyente_todos(
            tramite='FEDERAL',
            rfc=rfc
        ).order_by('folio')

        context['tramites_estatales'] = Visita_Detalle.objects.tramites_por_contribuyente_todos(
            tramite='ESTATAL',
            rfc=rfc
        ).order_by('folio')

        return context


class Alta_Programa(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Programa_Actualizaciones
    template_name = 'promocion/programas/alta_programa.html'
    form_class = ProgramaForm
    success_message = 'Programa Creado exitosamente!'

    def form_valid(self, form):
        form.instance.estatus = 'NUEVO'
        form.instance.usuario = get_username(self)

        return super(Alta_Programa, self).form_valid(form)

    def get_success_url(self):
        return self.request.META['HTTP_REFERER']


class Alta_Evento(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Evento
    template_name = 'promocion/eventos/alta_evento.html'
    form_class = EventoForm
    success_message = 'Evento Creado exitosamente!'

    def form_valid(self, form):
        form.instance.tipo = 'EN PROCESO'
        #form.instance.usuario = get_username(self)

        return super(Alta_Evento, self).form_valid(form)

    def get_success_url(self):
        return self.request.META['HTTP_REFERER']

class Alta_Desarrollo(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Desarrollo
    template_name = 'promocion/desarrollos/alta_desarrollo.html'
    form_class = DesarrolloForm
    success_message = 'Recorrido Creado exitosamente!'

    def form_valid(self, form):
        #form.instance.estatus = 'NUEVO'
        #form.instance.usuario = get_username(self)

        return super(Alta_Desarrollo, self).form_valid(form)

    def get_success_url(self):
        return self.request.META['HTTP_REFERER']


class Editar_Programa(LoginRequiredMixin, SuccessMessageMixin, UpdateView):    
    model = Programa_Actualizaciones
    template_name = 'promocion/programas/editar_programa.html'
    form_class = ProgramaForm
    success_message = 'Programa actualizado exitosamente!'

    def get_success_url(self):
        return self.request.META['HTTP_REFERER']


class Ver_Programa(LoginRequiredMixin, TemplateView):
    template_name = 'promocion/programas/ver_programa.html'

    def get_context_data(self, **kwargs):
        context = super(Ver_Programa, self).get_context_data(**kwargs)

        id_programa = self.kwargs.get('pk')

        context['detalle'] = Detalle.objects.filter(
            programa=id_programa
        ).order_by('fecha')

        return context


class Aprobar_Programa(LoginRequiredMixin, SuccessMessageMixin, TemplateView):
    template_name = 'promocion/programas/aprobar.html'
    success_message = 'Actualizado exitosamente!'

    def get_context_data(self, **kwargs):
        context = super(Aprobar_Programa, self).get_context_data(**kwargs)
        
        context['id_programa'] = self.kwargs['pk']

        context['form'] = AprobarForm    
        
        return context

    def post(self, request, *args, **kwargs):

templates/promocion/programas/alta_programa.html
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Crear Programa</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form id="form_alta_programa" action="{% url 'promocion_app:crear-programa' %}" method="POST"
            enctype="multipart/form-data">
            {% csrf_token %}

            <div class="modal-body p-4">
                
                <div class="row">
                    <div class="col-md-12">
                        <div class="mb-2">
                            {{ form.nombre.label }}
                            {{ form.nombre }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="mb-2">
                            {{ form.descripcion.label }}
                            {{ form.descripcion }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="mb-2">
                            {{ form.objetivo.label }}
                            {{ form.objetivo }}
                        </div>
                    </div>
                </div>

            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button id="btNew" type="submit" class="btn btn-primary">Guardar</button>
            </div>

        </form>
    </div>
</div>

<script>
    $(function () {

        $("#form_alta_programa").submit(function (e) {

            $("#btNew").attr("disabled", true);

            return true;

        });

    });

</script>

templates/promocion/programas/aprobar.html
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Aprobar Programa</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form id="form_alta_programa" action="{% url 'promocion_app:aprobar-programa' id_programa %}" method="POST"
            enctype="multipart/form-data">
            {% csrf_token %}

            <div class="modal-body p-4">

                <div class="row">
                    <div class="col-md-12">
                        <div class="mb-2">
                            {{ form.estatus.label }}
                            {{ form.estatus }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="mb-2">
                            {{ form.comentarios.label }}
                            {{ form.comentarios }}
                        </div>
                    </div>
                </div>

            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button id="btNew" type="submit" class="btn btn-primary">Guardar</button>
            </div>

        </form>
    </div>
</div>

templates/promocion/programas/editar_programa.html
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Editar Programa</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form id="form_alta_visita" action="{% url 'promocion_app:modificar-programa' object.id %}" method="POST">
            {% csrf_token %}

            <div class="modal-body p-4">
                <div class="row">
                    <div class="col-md-12">
                        <div class="mb-2">
                            {{ form.nombre.label }}
                            {{ form.nombre }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="mb-2">
                            {{ form.descripcion.label }}
                            {{ form.descripcion }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="mb-2">
                            {{ form.objetivo.label }}
                            {{ form.objetivo }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="mb-2">
                            {{ form.estatus }}
                        </div>
                    </div>
                </div>

            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <button id="btSave" type="submit" class="btn btn-primary">Guardar</button>
            </div>

        </form>
    </div>
</div>

templates/promocion/programas/ver_programa.html
{% load tags %}
<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Detalle</h4>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <div class="modal-body p-4">

            <div class="table-responsive">
                <table class="table table-sm mb-0">
                    <thead>
                        <tr class="text-dark">
                            <th>Fecha</th>
                            <th>Comentarios</th>
                            <th>Estatus</th>
                            <th>Usuario</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for row in detalle %}
                        <tr>
                            <td>{{ row.fecha|date:'d/m/Y' }}</td>
                            <td>{% if row.comentarios != None %}{{ row.comentarios }} {% endif %}</td>
                            <td>{{ row.estatus }}</td>
                            <td>
                                <div class="avatar-sm" title="{% get_user_info row.usuario %}" tabindex="0"
                                    data-plugin="tippy" data-tippy-placement="right">
                                    <span class="avatar-title bg-soft-warning text-secondary font-10 rounded-circle">
                                        {% get_initials row.usuario %}
                                    </span>
                                </div>
                            </td>

                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>


        </div>

        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        </div>
    </div>
</div>